### ISSUE TITLE
Various intllib-related crashes

### ISSUE THREAD

**Issue by Wayward1** [MrCerealGuy/Stonecraft#12]
While trying to start a new world, the game crashes while loading with the error
```2017-05-21 20:07:30: ERROR[Main]: cannot open /home/wayward_one/StoneCraft/bin/../games/stonecraft_game/mods/mesecons/mesecons_gates/intllib.lua: No such file or directory```. This happens for various mods, not just Mesecons.

**Comment by MrCerealGuy** [comment]
Thank you. I've forgotten to add this file to my remote git repository for several mods. You can now make a git pull.
